name: statline_dbt

profile: statline_dbt

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
    - "target"
    - "dbt_packages"

seeds:
    # Builds seeds into '<your_schema_name>_raw'
    statline_dbt_1:
        +schema: raw

models:
    statline_dbt_1:
        +static_analysis: strict
        # Materialize staging models as views, and marts as tables
        staging:
            +materialized: view
        marts:
            +materialized: table
