name: statline
version: "1.0.0"
config-version: 2

profile: statline

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  statline:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
