models:
  - name: dim_game
    columns:
      - name: game_id
        tests: [unique, not_null]
      - name: season
        tests: [not_null]
      - name: home_team
        tests: [not_null]
      - name: away_team
        tests: [not_null]
  - name: dim_player
    columns:
      - name: gsis_id
        tests: [unique, not_null]
  - name: dim_team
    columns:
      - name: team_abbr
        tests: [unique, not_null]
  - name: fact_player_game
    columns:
      - name: player_id
        tests: [not_null]
      - name: game_id
        tests: [not_null]
      - name: team_abbr
        tests: [not_null]
      - name: season
        tests: [not_null]
      - name: week
        tests: [not_null]
  - name: fact_team_game
    columns:
      - name: team_abbr
        tests: [not_null]
      - name: game_id
        tests: [not_null]
      - name: season
        tests: [not_null]
      - name: week
        tests: [not_null]
